import { db } from '@/db';
import { gallery } from '@/db/schema';

async function main() {
    const sampleGalleryItems = [
        {
            title: 'Advanced Hematology Analyzer',
            imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
            altText: 'Modern automated hematology analyzer processing blood samples',
            category: 'laboratory-equipment',
            description: 'State-of-the-art hematology analyzer capable of processing 120 samples per hour with complete blood count and differential analysis. Features advanced flow cytometry technology for precise cell counting and classification.',
            orderPosition: 0,
            status: 'active',
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            title: 'High-Resolution Digital Microscope',
            imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&h=600&fit=crop',
            altText: 'Digital microscope with high-resolution imaging capabilities',
            category: 'laboratory-equipment',
            description: 'Professional digital microscope with 40x to 1000x magnification range and integrated camera system. Enables detailed examination of blood cells, bacteria, and tissue samples with crystal-clear digital imaging.',
            orderPosition: 1,
            status: 'active',
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            title: 'Automated Sample Processing System',
            imageUrl: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&h=600&fit=crop',
            altText: 'Automated laboratory sample processing and sorting system',
            category: 'laboratory-equipment',
            description: 'Fully automated sample processing system that handles specimen sorting, labeling, and initial preparation. Reduces human error and increases efficiency with a capacity of 500 samples per hour.',
            orderPosition: 2,
            status: 'active',
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-09-01').toISOString(),
        },
        {
            title: 'Precision Centrifuge Station',
            imageUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&h=600&fit=crop',
            altText: 'High-speed laboratory centrifuge for sample separation',
            category: 'laboratory-equipment',
            description: 'High-speed refrigerated centrifuge with digital controls and safety features. Essential for separating blood components and preparing samples for various diagnostic tests with precise temperature control.',
            orderPosition: 3,
            status: 'active',
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            title: 'Modern Laboratory Clean Room',
            imageUrl: 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=800&h=600&fit=crop',
            altText: 'Sterile laboratory environment with modern equipment and proper ventilation',
            category: 'facilities',
            description: 'Climate-controlled clean room environment with HEPA filtration system and positive air pressure. Designed to maintain sterile conditions for sensitive diagnostic procedures and sample handling.',
            orderPosition: 4,
            status: 'active',
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            title: 'Patient Reception and Waiting Area',
            imageUrl: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=800&h=600&fit=crop',
            altText: 'Comfortable and modern patient waiting area with seating',
            category: 'facilities',
            description: 'Spacious and comfortable patient waiting area designed for privacy and relaxation. Features modern seating, natural lighting, and informational displays to ensure a pleasant patient experience.',
            orderPosition: 5,
            status: 'active',
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            title: 'Private Sample Collection Room',
            imageUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&h=600&fit=crop',
            altText: 'Clean and private sample collection room with medical equipment',
            category: 'facilities',
            description: 'Dedicated sample collection room with comfortable seating, proper lighting, and all necessary equipment for blood draws and specimen collection. Maintains patient privacy and comfort during procedures.',
            orderPosition: 6,
            status: 'active',
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            title: 'Executive Consultation Office',
            imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=600&fit=crop',
            altText: 'Professional consultation office for patient discussions',
            category: 'facilities',
            description: 'Private consultation office where medical professionals discuss test results with patients. Features comfortable seating, medical reference materials, and a professional atmosphere for sensitive conversations.',
            orderPosition: 7,
            status: 'active',
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            title: 'Laboratory Information Management System',
            imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
            altText: 'Computer workstation displaying laboratory management software',
            category: 'technology',
            description: 'Advanced LIMS workstation managing sample tracking, test scheduling, and result reporting. Integrates with all laboratory equipment for seamless workflow management and quality assurance.',
            orderPosition: 8,
            status: 'active',
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-01').toISOString(),
        },
        {
            title: 'Digital Imaging Workstation',
            imageUrl: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=800&h=600&fit=crop',
            altText: 'High-resolution monitor displaying microscopic images for analysis',
            category: 'technology',
            description: 'Professional imaging workstation with high-resolution monitors for detailed analysis of microscopic samples. Features specialized software for image enhancement and diagnostic interpretation.',
            orderPosition: 9,
            status: 'active',
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-10-05').toISOString(),
        },
        {
            title: 'Laboratory Technician at Work',
            imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&h=600&fit=crop',
            altText: 'Qualified laboratory technician operating diagnostic equipment',
            category: 'staff-at-work',
            description: 'Certified laboratory technician performing routine diagnostic tests using advanced equipment. Our skilled staff ensures accurate results through proper protocols and quality control measures.',
            orderPosition: 10,
            status: 'active',
            createdAt: new Date('2024-10-10').toISOString(),
            updatedAt: new Date('2024-10-10').toISOString(),
        },
        {
            title: 'Sample Collection Procedure',
            imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
            altText: 'Professional phlebotomist collecting blood sample from patient',
            category: 'staff-at-work',
            description: 'Trained phlebotomist performing safe and comfortable blood collection procedure. Our staff follows strict protocols to ensure patient safety and sample integrity for accurate test results.',
            orderPosition: 11,
            status: 'active',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            title: 'Quality Control Testing',
            imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=600&fit=crop',
            altText: 'Quality control samples being tested for accuracy verification',
            category: 'quality-safety',
            description: 'Daily quality control testing ensures all equipment functions within acceptable parameters. Control samples are run with each batch to verify accuracy and precision of all diagnostic tests.',
            orderPosition: 12,
            status: 'active',
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            title: 'Safety Protocol Implementation',
            imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop',
            altText: 'Laboratory safety equipment and protocols display',
            category: 'quality-safety',
            description: 'Comprehensive safety protocols including proper PPE usage, chemical handling procedures, and emergency response systems. Regular safety training ensures a secure working environment for all staff.',
            orderPosition: 13,
            status: 'active',
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            title: 'Accreditation Certificates Display',
            imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
            altText: 'Wall display of laboratory accreditation certificates and awards',
            category: 'quality-safety',
            description: 'Display of national and international accreditation certificates including ISO 15189, CAP, and NABL certifications. These credentials demonstrate our commitment to maintaining the highest quality standards.',
            orderPosition: 14,
            status: 'active',
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        }
    ];

    await db.insert(gallery).values(sampleGalleryItems);
    
    console.log('✅ Gallery seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});